import type { Metadata } from "next";

import "./globals.css";
import { Header } from "@/widgets/header";
import { MainLayout } from "@/shared/layouts/main";
import { Footer } from "@/widgets/footer";
import { Poppins, Roboto } from "next/font/google";
import { cn } from "@/shared/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

const poppins = Poppins({
  weight: ["400", "300", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen", roboto.variable, poppins.variable)}>
        <MainLayout header={<Header />} footer={<Footer />}>
          {children}
        </MainLayout>
      </body>
    </html>
  );
}
