import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Header} from "@/widgets/header";
import {MainLayout} from "@/shared/layouts/main";
import {Footer} from "@/widgets/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen">
      <MainLayout header={<Header />} footer={<Footer/>}>
          {children}
      </MainLayout>
      </body>
    </html>
  );
}
